import '../../features/auth/models/user_model.dart';
import '../../features/providers_list/models/service_provider_model.dart';

class DemoData {
  DemoData._();

  // ── Usuarios demo ──────────────────────────────────────────
  static final UserModel clientUser = UserModel(
    id: 'demo-client-001',
    email: 'cliente@demo.com',
    fullName: 'Ana Rodríguez',
    phone: '809-555-1234',
    role: UserRole.client,
    province: 'Distrito Nacional',
    city: 'Piantini',
    createdAt: DateTime(2024, 1, 15),
    isVerified: true,
  );

  static final UserModel providerUser = UserModel(
    id: 'demo-provider-001',
    email: 'prestador@demo.com',
    fullName: 'Carlos Méndez',
    phone: '809-555-4321',
    role: UserRole.provider,
    province: 'Distrito Nacional',
    city: 'Naco',
    createdAt: DateTime(2023, 6, 10),
    isVerified: true,
  );

  // ── Prestadores demo ────────────────────────────────────────
  static final List<ServiceProviderModel> providers = [
    ServiceProviderModel(
      id: 'prov-001',
      userId: 'demo-provider-001',
      fullName: 'Carlos Méndez',
      bio: 'Más de 5 años de experiencia en limpieza residencial y comercial. Puntual, confiable y con excelentes referencias.',
      rating: 4.9,
      reviewCount: 87,
      completedJobs: 134,
      services: [
        ProviderService(
          id: 'svc-001',
          categoryId: 'home_cleaning',
          categoryName: 'Limpieza del hogar',
          pricingType: PricingType.fixed,
          fixedPrice: 2500,
          priceDescription: 'Por hora, incluye materiales básicos',
        ),
        ProviderService(
          id: 'svc-002',
          categoryId: 'office_cleaning',
          categoryName: 'Limpieza de oficinas',
          pricingType: PricingType.quote,
          priceDescription: 'Cotización según m² del local',
          formFields: [
            ServiceFormField(
              id: 'area',
              label: 'Área aproximada (m²)',
              hint: 'Ej: 50',
              type: FormFieldType.number,
              required: true,
            ),
            ServiceFormField(
              id: 'frequency',
              label: 'Frecuencia del servicio',
              type: FormFieldType.select,
              required: true,
              options: ['Una vez', 'Semanal', 'Quincenal', 'Mensual'],
            ),
          ],
        ),
      ],
      province: 'Distrito Nacional',
      city: 'Naco',
      isAvailable: true,
      isVerified: true,
      photoUrls: [],
      memberSince: DateTime(2023, 6, 10),
      level: ProviderLevel.elite,       // 134 jobs → Elite 💎
    ),
    ServiceProviderModel(
      id: 'prov-002',
      userId: 'user-002',
      fullName: 'María González',
      bio: 'Especialista en cuidado de mascotas. Certificada en primeros auxilios para animales. Trato amoroso y profesional.',
      rating: 4.8,
      reviewCount: 62,
      completedJobs: 98,
      services: [
        ProviderService(
          id: 'svc-003',
          categoryId: 'pet_care',
          categoryName: 'Cuidado de mascotas',
          pricingType: PricingType.fixed,
          fixedPrice: 1500,
          priceDescription: 'Baño completo por mascota',
        ),
      ],
      province: 'Distrito Nacional',
      city: 'Bella Vista',
      isAvailable: true,
      isVerified: true,
      photoUrls: [],
      memberSince: DateTime(2023, 9, 5),
      level: ProviderLevel.experto,     // 98 jobs → Experto 🏆
    ),
    ServiceProviderModel(
      id: 'prov-003',
      userId: 'user-003',
      fullName: 'Luis Vargas',
      bio: 'Jardinero profesional con 8 años de experiencia. Especializado en diseño de jardines, poda y mantenimiento de zonas verdes.',
      rating: 4.7,
      reviewCount: 45,
      completedJobs: 78,
      services: [
        ProviderService(
          id: 'svc-004',
          categoryId: 'yard_maintenance',
          categoryName: 'Mantenimiento de patios',
          pricingType: PricingType.quote,
          priceDescription: 'Precio según tamaño del área',
          formFields: [
            ServiceFormField(
              id: 'area_size',
              label: 'Tamaño del patio',
              type: FormFieldType.select,
              required: true,
              options: ['Pequeño (< 50m²)', 'Mediano (50-150m²)', 'Grande (> 150m²)'],
            ),
            ServiceFormField(
              id: 'service_type',
              label: 'Tipo de servicio',
              type: FormFieldType.select,
              required: true,
              options: ['Poda básica', 'Limpieza completa', 'Diseño y siembra'],
            ),
          ],
        ),
      ],
      province: 'Santiago',
      city: 'Santiago de los Caballeros',
      isAvailable: true,
      isVerified: false,
      photoUrls: [],
      memberSince: DateTime(2024, 2, 20),
      level: ProviderLevel.destacado,   // 10+ jobs → Destacado ⭐
    ),
    ServiceProviderModel(
      id: 'prov-004',
      userId: 'user-004',
      fullName: 'Roberto Jiménez',
      bio: 'Lavado de vehículos a domicilio. Llevo todos los equipos. Lavado exterior, interior, motor y encerado profesional.',
      rating: 4.6,
      reviewCount: 31,
      completedJobs: 55,
      services: [
        ProviderService(
          id: 'svc-005',
          categoryId: 'car_wash',
          categoryName: 'Lavado de vehículos',
          pricingType: PricingType.fixed,
          fixedPrice: 800,
          priceDescription: 'Lavado exterior e interior',
        ),
        ProviderService(
          id: 'svc-006',
          categoryId: 'car_wash',
          categoryName: 'Lavado con encerado',
          pricingType: PricingType.fixed,
          fixedPrice: 1500,
          priceDescription: 'Lavado completo + encerado profesional',
        ),
      ],
      province: 'Santo Domingo',
      city: 'Santo Domingo Este',
      isAvailable: false,
      isVerified: true,
      photoUrls: [],
      memberSince: DateTime(2024, 3, 1),
      level: ProviderLevel.destacado,
    ),
    ServiceProviderModel(
      id: 'prov-005',
      userId: 'user-005',
      fullName: 'Sofía Mora',
      bio: 'Servicio de mudanzas y carga con vehículo propio. Responsable, cuidadosa con sus pertenencias y puntual.',
      rating: 4.5,
      reviewCount: 19,
      completedJobs: 28,
      services: [
        ProviderService(
          id: 'svc-007',
          categoryId: 'moving',
          categoryName: 'Mudanzas y carga',
          pricingType: PricingType.quote,
          priceDescription: 'Cotización según distancia y volumen',
          formFields: [
            ServiceFormField(
              id: 'origin',
              label: 'Origen de la mudanza',
              hint: 'Ciudad / sector',
              type: FormFieldType.text,
              required: true,
            ),
            ServiceFormField(
              id: 'destination',
              label: 'Destino',
              hint: 'Ciudad / sector',
              type: FormFieldType.text,
              required: true,
            ),
            ServiceFormField(
              id: 'volume',
              label: 'Cantidad de muebles',
              type: FormFieldType.select,
              required: true,
              options: ['Poco (1 cuarto)', 'Medio (2-3 cuartos)', 'Mucho (casa completa)'],
            ),
          ],
        ),
      ],
      province: 'Santo Domingo',
      city: 'Los Alcarrizos',
      isAvailable: true,
      isVerified: false,
      photoUrls: [],
      memberSince: DateTime(2024, 4, 15),
      level: ProviderLevel.newLevel,
    ),
  ];

  // ── Reseñas demo ────────────────────────────────────────────
  static final List<ReviewModel> reviewsForProv001 = [
    ReviewModel(
      id: 'rev-001',
      clientId: 'demo-client-001',
      clientName: 'Ana Rodríguez',
      rating: 5.0,
      comment: 'Excelente trabajo, muy puntual y dejó la casa impecable. Lo recomiendo al 100%.',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    ReviewModel(
      id: 'rev-002',
      clientId: 'client-002',
      clientName: 'Pedro Castillo',
      rating: 5.0,
      comment: 'Muy buen servicio, profesional y honesto. Ya lo contraté por segunda vez.',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    ReviewModel(
      id: 'rev-003',
      clientId: 'client-003',
      clientName: 'Laura Fernández',
      rating: 4.5,
      comment: 'Buen trabajo en general. Llegó un poco tarde pero el resultado fue excelente.',
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
    ),
  ];

  // ── Reservas demo (para el cliente) ─────────────────────────
  static final List<Map<String, dynamic>> clientBookings = [
    {
      'id': 'book-001',
      'client_id': 'demo-client-001',
      'client_name': 'Ana Rodríguez',
      'provider_id': 'prov-001',
      'provider_name': 'Carlos Méndez',
      'service_id': 'svc-001',
      'service_name': 'Limpieza del hogar',
      'status': 'completed',
      'payment_status': 'paid',
      'scheduled_date': DateTime.now().subtract(const Duration(days: 5)).toIso8601String(),
      'address': 'Piantini, Av. Abraham Lincoln, Edif. Torres Piantini',
      'agreed_price': 2500,
      'notes': null,
      'created_at': DateTime.now().subtract(const Duration(days: 7)).toIso8601String(),
    },
    {
      'id': 'book-002',
      'client_id': 'demo-client-001',
      'client_name': 'Ana Rodríguez',
      'provider_id': 'prov-002',
      'provider_name': 'María González',
      'service_id': 'svc-003',
      'service_name': 'Cuidado de mascotas',
      'status': 'accepted',
      'payment_status': 'pending',
      'scheduled_date': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
      'address': 'Bella Vista, Av. Sarasota esq. Max Henríquez Ureña',
      'agreed_price': 1500,
      'notes': 'Mi perro se llama Max, es golden retriever.',
      'created_at': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    },
    {
      'id': 'book-003',
      'client_id': 'demo-client-001',
      'client_name': 'Ana Rodríguez',
      'provider_id': 'prov-004',
      'provider_name': 'Roberto Jiménez',
      'service_id': 'svc-005',
      'service_name': 'Lavado de vehículos',
      'status': 'pending',
      'payment_status': 'pending',
      'scheduled_date': DateTime.now().add(const Duration(days: 4)).toIso8601String(),
      'address': 'Santiago, frente al Monumento a los Héroes',
      'agreed_price': 800,
      'notes': null,
      'created_at': DateTime.now().toIso8601String(),
    },
  ];

  // ── Reservas demo (para el prestador) ───────────────────────
  static final List<Map<String, dynamic>> providerBookings = [
    {
      'id': 'book-p001',
      'client_id': 'demo-client-001',
      'client_name': 'Ana Rodríguez',
      'provider_id': 'prov-001',
      'provider_name': 'Carlos Méndez',
      'service_id': 'svc-001',
      'service_name': 'Limpieza del hogar',
      'status': 'pending',
      'payment_status': 'pending',
      'scheduled_date': DateTime.now().add(const Duration(days: 1)).toIso8601String(),
      'address': 'Naco, Calle El Número, Residencial Los Álamos',
      'agreed_price': 2500,
      'notes': 'Casa de 3 habitaciones, 2 baños.',
      'created_at': DateTime.now().subtract(const Duration(hours: 3)).toIso8601String(),
    },
    {
      'id': 'book-p002',
      'client_id': 'client-009',
      'client_name': 'Jorge Ramírez',
      'provider_id': 'prov-001',
      'provider_name': 'Carlos Méndez',
      'service_id': 'svc-002',
      'service_name': 'Limpieza de oficinas',
      'status': 'pending',
      'payment_status': 'pending',
      'scheduled_date': DateTime.now().add(const Duration(days: 3)).toIso8601String(),
      'address': 'Naco, Torre Empresarial Reyna, piso 4',
      'agreed_price': null,
      'notes': 'Oficina de 80m², necesita cotización.',
      'created_at': DateTime.now().subtract(const Duration(hours: 8)).toIso8601String(),
    },
    {
      'id': 'book-p003',
      'client_id': 'client-010',
      'client_name': 'Valeria Soto',
      'provider_id': 'prov-001',
      'provider_name': 'Carlos Méndez',
      'service_id': 'svc-001',
      'service_name': 'Limpieza del hogar',
      'status': 'completed',
      'payment_status': 'paid',
      'scheduled_date': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
      'address': 'Santo Domingo Este, Ensanche Ozama',
      'agreed_price': 5000,
      'notes': null,
      'created_at': DateTime.now().subtract(const Duration(days: 6)).toIso8601String(),
    },
  ];
}
